// constants
export const TASKS_ADD_TASK = "TASKS_ADD_TASK";
export const TASKS_DELETE_TASK = "TASKS_DELETE_TASK";
export const TASKS_DELETE_ALL_TASK = "TASKS_DELETE_ALL_TASK";
export const TASKS_DONE_TASK = "TASKS_DONE_TASK";
export const TASKS_EDIT_TASK = "TASKS_EDIT_TASK";
